#!/usr/bin/with-contenv bash

source /etc/env

if [[ $APP == "radarr" ]]; then
    exec s6-setuidgid hotio mono --debug /app/Radarr.exe --nobrowser --data=/config $ARGS
fi

if [[ $APP == "sonarr" ]]; then
    exec s6-setuidgid hotio mono --debug /app/NzbDrone.exe --nobrowser --data=/config $ARGS
fi

if [[ $APP == "lidarr" ]]; then
    exec s6-setuidgid hotio mono --debug /app/Lidarr.exe --nobrowser --data=/config $ARGS
fi

if [[ $APP == "phantom" ]]; then
    exec s6-setuidgid hotio mono --debug /app/Sonarr.exe --nobrowser --data=/config $ARGS
fi

if [[ $APP == "jackett" ]]; then
    exec s6-setuidgid hotio mono --debug /app/JackettConsole.exe --NoRestart --ListenPublic $ARGS
fi

if [[ $APP == "nzbhydra" ]]; then
    exec s6-setuidgid hotio python /app/nzbhydra.py --nobrowser --config /config/nzbhydra.cfg --database /config/nzbhydra.db --logfile /config/nzbhydra.log $ARGS
fi

if [[ $APP == "nzbhydra2" ]]; then
    exec s6-setuidgid hotio /app/nzbhydra2 --nobrowser --datafolder /config $ARGS
fi

if [[ $APP == "nzbget" ]]; then
    exec s6-setuidgid hotio /app/nzbget --server --option OutputMode=log --configfile /config/nzbget.conf $ARGS
fi
