#!/usr/bin/with-contenv bash

source /etc/env

if [[ $BACKUP == "yes" ]]; then
    mkdir -p /config/backups-suitarr

    if [[ $APP == "radarr" ]]; then
        tar -czf /config/backups-suitarr/radarr_backup_$(date +%Y.%m.%d_%H.%M.%S).tar.gz -C /config nzbdrone.db config.xml
    fi

    if [[ $APP == "lidarr" ]]; then
        tar -czf /config/backups-suitarr/lidarr_backup_$(date +%Y.%m.%d_%H.%M.%S).tar.gz -C /config nzbdrone.db config.xml
    fi

    if [[ $APP == "sonarr" ]]; then
        tar -czf /config/backups-suitarr/sonarr_backup_$(date +%Y.%m.%d_%H.%M.%S).tar.gz -C /config nzbdrone.db config.xml
    fi

    if [[ $APP == "phantom" ]]; then
        tar -czf /config/backups-suitarr/phantom_backup_$(date +%Y.%m.%d_%H.%M.%S).tar.gz -C /config nzbdrone.db sonarr.db config.xml
    fi

    if [[ $APP == "jackett" ]]; then
        tar -czf /config/backups-suitarr/jackett_backup_$(date +%Y.%m.%d_%H.%M.%S).tar.gz -C /config Jackett/ServerConfig.json Jackett/Indexers .mono
    fi

    if [[ $APP == "nzbhydra" ]]; then
        tar -czf /config/backups-suitarr/nzbhydra_backup_$(date +%Y.%m.%d_%H.%M.%S).tar.gz -C /config nzbhydra.cfg nzbhydra.db
    fi

    if [[ $APP == "nzbget" ]]; then
        tar -czf /config/backups-suitarr/nzbget_backup_$(date +%Y.%m.%d_%H.%M.%S).tar.gz -C /config nzbget.conf
    fi

    chown -R hotio:hotio /config/backups-suitarr
fi
