#!/usr/bin/with-contenv bash

source /etc/env

if [[ $APP == "radarr" ]] || [[ $APP == "sonarr" ]] || [[ $APP == "lidarr" ]] ; then
    [[ -f /config/nzbdrone.pid ]] && rm /config/nzbdrone.pid
fi

if [[ $APP == "nzbhydra" ]]; then
    mkdir -p /config/backup && ln -s /config/backup /app/backup
fi

if [[ $APP == "nzbget" ]]; then
    [[ -f /config/nzbget.lock ]] && rm /config/nzbget.lock

    if [[ ! -f /config/nzbget.conf ]]; then
        cat /app/nzbget.conf | sed -e "s#\(MainDir=\).*#\1/config/downloads#g" \
                                   -e "s#\(QueueDir=\).*#\1/config/queue#g" \
                                   -e "s#\(TempDir=\).*#\1/config/tmp#g" \
                                   -e "s#\(LockFile=\).*#\1/config/nzbget.lock#g" \
                                   -e "s#\(LogFile=\).*#\1/config/nzbget.log#g" \
                                   > /config/nzbget.conf
    fi
fi

chown -R hotio:hotio /config
